### ISSUE TITLE
Certbot fails to run with wrong idna version

### ISSUE THREAD

**Issue by ArcolaJasper** [thefinn93/ansible-letsencrypt#58]
Hi,

Certbot has started failing with:

> An unexpected error occurred:", "ContextualVersionConflict: (idna 2.6 (/usr/local/share/letsencrypt/env/lib/python2.7/site-packages), Requirement.parse('idna<2.6,>=2.5'), set(['requests']))

There is a certbot bug open here:

https://github.com/certbot/certbot/issues/5015

They say that installing via pip is not supported and we should use the version from jessie-backports when on Debian jessie.

**Comment by nbering** [comment]
There's also an active discussion on the [Let's Encrypt Community Forum](https://community.letsencrypt.org/t/renew-certificates-contextualversionconflict/39826?u=nbering).

I'm encountering the same issue, and it would seem everyone else who installed with pip instead of the apt package is as well.

I found a workaround for the moment is to let the role fail, and then run the install the right idna version in the virtualenv and run the commands manually. That at least got me a cert for now, but running the role again overrides my manual version install.

To install the correct version on the target machine:
```bash
sudo /usr/local/share/letsencrypt/env/bin/pip install "idna<2.6,>=2.5"
```

The command it would have run can be copied from the ansible error output.

Once you have a certificate the role won't try to run the command again because the certificate file exists, which will at least help people get through their server setups for today...

**Comment by ArcolaJasper** [comment]
partly working now:

https://github.com/ArcolaJasper/ansible-letsencrypt

**Comment by ArcolaJasper** [comment]
Rough and ready PR:

https://github.com/thefinn93/ansible-letsencrypt/pull/59

**Comment by thefinn93** [comment]
Cool! Please fix the merge issues so I can merge it (reviewing further now)

**Comment by ArcolaJasper** [comment]
Hi,

I've merged it now.

**Comment by thefinn93** [comment]
```yaml
  - name: check for Debian != jessie
    fail:
      msg: "Only the jessie release of Debian is supported at the moment"
when: ansible_distribution == "Debian" and ansible_distribution_release != "jessie"
```

Perhaps we could not refuse to run on non-jessie versions of Debian? Jessie isn't even the stable version anymore. Maybe just run the notdebian.yml in that case

**Comment by thefinn93** [comment]
Actually, I'm going to close this and move discussion to the pull request's comment thread (#59)
